### PR TITLE
Fix an edge case creating non-minimal ranges

### LINKED ISSUE #37: Non-minimal regex when adding a second range lower than the first
With the specific following instructions, regenerate produces a non-minimal (but correct) regex:
```js
regenerate().addRange( 99, 100 ).addRange( 65, 99 ).toString()
'[cdA-c]'
```
By switching the order, we have a correct minimal regex:
```js
regenerate().addRange( 65, 99 ).addRange( 99, 100 ).toString()
'[A-d]'
```
Playing a bit with the boundaries, it seems it only occur when the end of the second range is exactly the same as the start of the first range.

### PR DESCRIPTION
**Pull request by Seb35**
Closes #37.

### CODE REVIEW

**Comment by Seb35** [comment]
See #39 to fix Travis - it’s better to merge #39 before and then rebase this one to make the CI happy.

Also, just a detail not linked to this issue: the version written in various files is 1.3.3 but the npm version is 1.4.0.

**Comment by mathiasbynens** [comment]
Thanks!

**Comment by mathiasbynens** [comment]
> Also, just a detail not linked to this issue: the version written in various files is 1.3.3 but the npm version is 1.4.0.

Thanks for calling that out too! I've fixed this for the new v1.4.1 release.

**Comment by Seb35** [comment]
I have to thank you also for this library and your work around Unicode and JavaScript! I intend to use regenerate in PEG.js, specifically to solve https://github.com/pegjs/pegjs/issues/586.

**Comment by mathiasbynens** [comment]
Awesome! Nice work on the patches there, and thank you for letting me know!

**Pull request merged**
